<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * PHASE 4 - MODEL: PlatformRiskFlag
 * 
 * PURPOSE:
 * Stores automated risk detection signals generated by platform analysis.
 * 
 * CRITICAL SAFEGUARDS:
 * - These are INFORMATIONAL FLAGS, not investment ratings
 * - Flags highlight patterns that may warrant investor attention
 * - Platform shows methodology transparently (how flag was detected)
 * - Companies cannot edit or suppress flags
 * 
 * REGULATORY COMPLIANCE:
 * - Flags are based on disclosed data, not predictions
 * - Language is neutral and factual (e.g., "cash flow negative" not "bad investment")
 * - Full detection logic is documented and accessible
 * - No recommendations (e.g., "don't invest" or "buy")
 * 
 * EXAMPLES OF SAFE FLAGS:
 * ✅ "Revenue declined 3 consecutive quarters (based on disclosed financials)"
 * ✅ "Board has 0 independent directors (based on disclosed governance)"
 * ✅ "Company disclosed 12 critical-severity risk factors"
 * ❌ "This is a risky investment" (too subjective)
 * ❌ "Company will likely fail" (predictive)
 *
 * @property int $id
 * @property int $company_id
 * @property string $flag_type
 * @property string $severity
 * @property string $category
 * @property string $description
 * @property string $detection_logic
 * @property array|null $supporting_data
 * @property array|null $context
 * @property int|null $disclosure_id
 * @property string|null $disclosure_field_path
 * @property string $status
 * @property \Carbon\Carbon $detected_at
 * @property \Carbon\Carbon|null $resolved_at
 * @property string|null $resolution_notes
 * @property bool $is_visible_to_investors
 * @property string|null $investor_message
 * @property string $detection_version
 * @property array|null $metadata
 * @mixin IdeHelperPlatformRiskFlag
 */
class PlatformRiskFlag extends Model
{
    use HasFactory;

    protected $table = 'platform_risk_flags';

    protected $fillable = [
        'company_id',
        'flag_type',
        'severity',
        'category',
        'description',
        'detection_logic',
        'supporting_data',
        'context',
        'disclosure_id',
        'disclosure_field_path',
        'status',
        'detected_at',
        'resolved_at',
        'resolution_notes',
        'is_visible_to_investors',
        'investor_message',
        'detection_version',
        'metadata',
    ];

    protected $casts = [
        'supporting_data' => 'array',
        'context' => 'array',
        'detected_at' => 'datetime',
        'resolved_at' => 'datetime',
        'is_visible_to_investors' => 'boolean',
        'metadata' => 'array',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
    ];

    // =========================================================================
    // FLAG TYPE CONSTANTS
    // =========================================================================
    // REGULATORY NOTE: All flag types are FACTUAL OBSERVATIONS, not predictions

    // Financial Flags (based on disclosed financials)
    public const FLAG_NEGATIVE_CASH_FLOW = 'negative_operating_cash_flow';
    public const FLAG_DECLINING_REVENUE = 'consecutive_revenue_decline';
    public const FLAG_HIGH_BURN_RATE = 'high_cash_burn_rate';
    public const FLAG_NEGATIVE_MARGINS = 'negative_profit_margins';
    public const FLAG_INCOMPLETE_FINANCIALS = 'incomplete_financial_disclosure';

    // Governance Flags (based on disclosed governance)
    public const FLAG_NO_INDEPENDENT_DIRECTORS = 'no_independent_directors';
    public const FLAG_SMALL_BOARD = 'board_below_minimum_size';
    public const FLAG_MISSING_COMMITTEES = 'missing_governance_committees';
    public const FLAG_RELATED_PARTY_TRANSACTIONS = 'significant_related_party_transactions';

    // Legal/Compliance Flags (based on disclosed legal matters)
    public const FLAG_PENDING_LITIGATION = 'material_pending_litigation';
    public const FLAG_REGULATORY_INVESTIGATION = 'active_regulatory_investigation';
    public const FLAG_COMPLIANCE_VIOLATIONS = 'disclosed_compliance_violations';

    // Disclosure Quality Flags (based on disclosure completeness)
    public const FLAG_INCOMPLETE_DISCLOSURE = 'incomplete_required_disclosures';
    public const FLAG_STALE_DATA = 'outdated_financial_data';
    public const FLAG_MISSING_RISK_FACTORS = 'insufficient_risk_disclosures';
    public const FLAG_VAGUE_DISCLOSURES = 'vague_or_generic_disclosures';

    // Market/Operational Flags (based on disclosed operations)
    public const FLAG_CONCENTRATED_CUSTOMER_BASE = 'high_customer_concentration';
    public const FLAG_SINGLE_PRODUCT_REVENUE = 'single_product_dependency';
    public const FLAG_KEY_PERSON_RISK = 'key_person_dependency_risk';

    // =========================================================================
    // RELATIONSHIPS
    // =========================================================================

    /**
     * Company this flag belongs to
     */
    public function company()
    {
        return $this->belongsTo(Company::class);
    }

    /**
     * Disclosure that triggered this flag (if applicable)
     */
    public function disclosure()
    {
        return $this->belongsTo(CompanyDisclosure::class, 'disclosure_id');
    }

    // =========================================================================
    // ACCESSOR METHODS
    // =========================================================================

    /**
     * Get severity color for UI display
     */
    public function getSeverityColor(): string
    {
        return match($this->severity) {
            'info' => 'blue',
            'low' => 'green',
            'medium' => 'yellow',
            'high' => 'orange',
            'critical' => 'red',
            default => 'gray',
        };
    }

    /**
     * Get category display name
     */
    public function getCategoryDisplayName(): string
    {
        return match($this->category) {
            'financial' => 'Financial',
            'governance' => 'Governance',
            'legal' => 'Legal & Compliance',
            'disclosure_quality' => 'Disclosure Quality',
            'market' => 'Market & Competition',
            'operational' => 'Operational',
            default => ucfirst($this->category),
        };
    }

    /**
     * Get investor-facing summary of this flag
     *
     * REGULATORY NOTE: Includes detection methodology for transparency
     *
     * @return array
     */
    public function getInvestorSummary(): array
    {
        return [
            'flag_id' => $this->id,
            'category' => $this->getCategoryDisplayName(),
            'severity' => $this->severity,
            'message' => $this->investor_message ?? $this->description,
            'detected_at' => $this->detected_at,
            'status' => $this->status,
            'transparency' => [
                'detection_logic' => $this->detection_logic,
                'supporting_data' => $this->supporting_data,
                'context' => $this->context,
            ],
            'source' => [
                'disclosure_id' => $this->disclosure_id,
                'field_path' => $this->disclosure_field_path,
            ],
            'disclaimer' => 'This flag is based on disclosed information and platform analysis. It does not constitute investment advice. Investors should review the underlying disclosures and conduct their own due diligence.',
        ];
    }

    // =========================================================================
    // HELPER METHODS
    // =========================================================================

    /**
     * Mark flag as resolved
     */
    public function resolve(string $resolutionNotes): void
    {
        $this->update([
            'status' => 'resolved',
            'resolved_at' => now(),
            'resolution_notes' => $resolutionNotes,
        ]);

        \Log::info('Platform risk flag resolved', [
            'flag_id' => $this->id,
            'flag_type' => $this->flag_type,
            'company_id' => $this->company_id,
            'resolution' => $resolutionNotes,
        ]);
    }

    /**
     * Check if flag is active
     */
    public function isActive(): bool
    {
        return $this->status === 'active';
    }

    /**
     * Check if flag should be shown to investors
     */
    public function isVisibleToInvestors(): bool
    {
        return $this->is_visible_to_investors && $this->status === 'active';
    }

    // =========================================================================
    // SCOPES
    // =========================================================================

    /**
     * Scope to active flags
     */
    public function scopeActive($query)
    {
        return $query->where('status', 'active');
    }

    /**
     * Scope to flags visible to investors
     */
    public function scopeVisibleToInvestors($query)
    {
        return $query->where('is_visible_to_investors', true)
            ->where('status', 'active');
    }

    /**
     * Scope to flags by category
     */
    public function scopeCategory($query, string $category)
    {
        return $query->where('category', $category);
    }

    /**
     * Scope to flags by severity
     */
    public function scopeSeverity($query, string $severity)
    {
        return $query->where('severity', $severity);
    }

    /**
     * Scope to high or critical severity flags
     */
    public function scopeHighSeverity($query)
    {
        return $query->whereIn('severity', ['high', 'critical']);
    }

    /**
     * Scope to flags for specific company
     */
    public function scopeForCompany($query, int $companyId)
    {
        return $query->where('company_id', $companyId);
    }
}
