<?php
// V-DEPLOY-1730-007
namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     * This is the MASTER seeder file.
     * It calls all other seeders in the correct order.
     */
    public function run(): void
    {
        // 1. Roles & Permissions must come first
        $this->call(RolesAndPermissionsSeeder::class);

        // 2. Settings seeder
        $this->call(SettingsSeeder::class);

        // 3. User seeder (to create admin and test users)
        $this->call(UserSeeder::class);

        // 4. Product seeder (to create dummy companies)
        $this->call(ProductSeeder::class);

        // 5. Plan seeder (to create Plans A, B, C, D)
        $this->call(PlanSeeder::class);
        
        // Note: We don't seed transactional tables like payments,
        // subscriptions, or bonuses, as those should be
        // generated by your own testing.
    }
}