// components/aml/AmlKycPart5.tsx
'use client';

import React from "react";

export default function AmlKycPart5() {
  return (
    <div>

      {/* 8.2.3 RULE CALIBRATION AND TUNING */}
      <section id="rule-calibration" className="section">
        <div className="section-header">
          <span className="section-number">08.2.3</span>
          <h2 className="section-title">Rule Calibration and Tuning</h2>
        </div>

        <h3>(a) Rules reviewed quarterly for effectiveness based on:</h3>
        <ul className="legal-list">
          <li>Alert volume (avoiding excessive false positives)</li>
          <li>True positive rate (confirmed suspicious activities detected)</li>
          <li>Emerging typologies and regulatory guidance</li>
        </ul>

        <h3>(b) Thresholds adjusted based on:</h3>
        <ul className="legal-list">
          <li>Platform's transaction volume and value distribution</li>
          <li>Regulatory threshold changes</li>
          <li>Money laundering trend analysis</li>
        </ul>

        <h3>(c) New rules added based on:</h3>
        <ul className="legal-list">
          <li>FIU-IND typology reports</li>
          <li>Regulatory circulars and guidance</li>
          <li>Industry best practices</li>
          <li>Platform's own suspicious activity detection</li>
        </ul>

        <h3>(d) Rule changes approved by:</h3>
        <ul className="legal-list">
          <li>Principal Officer for minor threshold adjustments</li>
          <li>Designated Director for structural rule changes</li>
          <li>Board notification for material changes to monitoring framework</li>
        </ul>
      </section>

      {/* 8.3 ALERT MANAGEMENT AND INVESTIGATION PROCEDURES */}
      <section id="alert-management" className="section">
        <div className="section-header">
          <span className="section-number">08.3</span>
          <h2 className="section-title">Alert Management and Investigation Procedures</h2>
        </div>

        <h3>8.3.1 Alert Prioritization</h3>
        <p>Alerts generated by monitoring system prioritized as:</p>

        <h4>(a) Priority 1 — Critical (Red Flag):</h4>
        <ul className="legal-list">
          <li>Sanctions list match or potential match</li>
          <li>PEP with corruption indicators</li>
          <li>High-value transaction with no economic rationale</li>
          <li>Multiple severe red flags</li>
          <li>SLA: Investigation commenced within 2 hours; Initial assessment within 24 hours</li>
        </ul>

        <h4>(b) Priority 2 — High (Red Flag):</h4>
        <ul className="legal-list">
          <li>Single severe red flag or multiple moderate flags</li>
          <li>High-value transactions requiring approval</li>
          <li>Structuring indicators</li>
          <li>Significant profile inconsistency</li>
          <li>SLA: Investigation commenced within 24 hours; Initial assessment within 72 hours</li>
        </ul>

        <h4>(c) Priority 3 — Medium (Yellow Flag):</h4>
        <ul className="legal-list">
          <li>Single moderate red flag</li>
          <li>Threshold exceedance</li>
          <li>Behavioral anomalies</li>
          <li>SLA: Review within 72 hours; Assessment within 5 business days</li>
        </ul>

        <h4>(d) Priority 4 — Low (Yellow Flag):</h4>
        <ul className="legal-list">
          <li>Minor deviations or informational alerts</li>
          <li>Routine enhanced monitoring triggers</li>
          <li>SLA: Review within 5 business days</li>
        </ul>

        {/* 8.3.2 Investigation Process */}
        <h3>8.3.2 Investigation Process</h3>
        <p>For each alert, the designated investigator shall:</p>

        <h4>(a) Step 1 — Information Gathering (Day 0–1):</h4>
        <ul className="legal-list">
          <li>Retrieve complete Customer KYC file</li>
          <li>Review entire transaction history</li>
          <li>Gather details of specific flagged transaction(s)</li>
          <li>Review Customer profile & risk rating</li>
          <li>Check prior alerts/investigations</li>
          <li>Identify related/connected accounts</li>
        </ul>

        <h4>(b) Step 2 — Analysis (Day 1–2):</h4>
        <ul className="legal-list">
          <li>Compare transaction vs profile</li>
          <li>Assess economic rationale</li>
          <li>Identify patterns or connections</li>
          <li>Review source of funds documentation</li>
          <li>Analyze counterparty (if relevant)</li>
          <li>Adverse media, sanctions, legal database checks</li>
        </ul>

        <h4>(c) Step 3 — Customer Interaction (Day 2–3, if required):</h4>
        <ul className="legal-list">
          <li>Contact Customer for explanation</li>
          <li>Request additional documents</li>
          <li>Document responses verbatim</li>
          <li>Assess credibility</li>
          <li>Escalate if unsatisfactory</li>
        </ul>

        <h4>(d) Step 4 — Assessment and Disposition (Day 3–5):</h4>

        <h5>Finding: Not Suspicious</h5>
        <ul className="legal-list">
          <li>Document rationale</li>
          <li>Update Customer profile</li>
          <li>Close alert</li>
        </ul>

        <h5>Finding: Suspicious</h5>
        <ul className="legal-list">
          <li>Immediate escalation to Principal Officer</li>
          <li>Detailed investigation report</li>
          <li>Hold transaction</li>
          <li>No tipping-off</li>
        </ul>

        <h5>Finding: Requires Enhanced Monitoring</h5>
        <ul className="legal-list">
          <li>Clear transaction but flag Customer</li>
          <li>Risk rating upgrade if needed</li>
          <li>Set monitoring parameters and review date</li>
        </ul>

        <h4>(e) Step 5 — Documentation:</h4>
        <ul className="legal-list">
          <li>Complete case notes</li>
          <li>Attach documents</li>
          <li>Disposition rationale</li>
          <li>Supervisor approval</li>
          <li>Archive for audit</li>
        </ul>

        {/* 8.3.3 Escalation */}
        <h3>8.3.3 Escalation to Principal Officer</h3>
        <p>Escalation mandatory when:</p>

        <ul className="legal-list">
          <li>(a) Potential ML/TF;</li>
          <li>(b) Unsatisfactory Customer explanation;</li>
          <li>(c) No economic rationale;</li>
          <li>(d) Multiple red flags;</li>
          <li>(e) ≥ ₹50,00,000 high-value flagged;</li>
          <li>(f) PEP with integrity concerns;</li>
          <li>(g) Sanctions match;</li>
          <li>(h) Investigator uncertain.</li>
        </ul>

        <p>Principal Officer shall:</p>
        <ul className="legal-list">
          <li>Review all materials</li>
          <li>Conduct additional inquiries</li>
          <li>Determine disposition: Clear / Enhanced Monitoring / STR</li>
          <li>Document reasoning</li>
          <li>Provide investigator feedback</li>
        </ul>

        {/* 8.3.4 Transaction Hold Procedures */}
        <h3>8.3.4 Transaction Hold Procedures</h3>

        <ul className="legal-list">
          <li>(a) System blocks completion</li>
          <li>(b) Notify Customer: “routine verification”</li>
          <li>(c) Provide timeline: 3–5 business days</li>
          <li>(d) If &gt;5 days → periodic updates</li>
          <li>(e) If STR filed → reject/hold longer</li>
          <li>(f) If no issues → process immediately</li>
        </ul>

        {/* 8.3.5 Record Retention */}
        <h3>8.3.5 Record Retention</h3>

        <p>All alert investigations retained for 10 years:</p>
        <ul className="legal-list">
          <li>Alert details</li>
          <li>Investigation notes</li>
          <li>Customer communications</li>
          <li>Uploaded documents</li>
          <li>Disposition rationale</li>
          <li>Supervisor approvals</li>
          <li>STR (if any)</li>
        </ul>

      </section>

      {/* 9. RED FLAG INDICATORS */}
      <section id="red-flags" className="section">
        <div className="section-header">
          <span className="section-number">09</span>
          <h2 className="section-title">RED FLAG INDICATORS — PRE-IPO MARKET SPECIFIC</h2>
        </div>

        {/* 9.1 Customer Behavior */}
        <h3>9.1 Customer Behavior Red Flags</h3>

        <h4>9.1.1 Onboarding Stage Red Flags</h4>

        <h5>(a) Identity and Documentation Issues:</h5>
        <ul className="legal-list">
          <li>Reluctance to provide complete KYC</li>
          <li>Forged/altered/poor-quality documents</li>
          <li>Multiple persons with identical address/contacts</li>
          <li>Document-mill indicators</li>
          <li>PAN–Aadhaar mismatch</li>
          <li>Unable to answer basic KYC questions</li>
          <li>Use of third-party documents</li>
        </ul>

        <h5>(b) Evasive or Suspicious Behavior:</h5>
        <ul className="legal-list">
          <li>Reluctance on SoF/SoW</li>
          <li>Inconsistent explanations</li>
          <li>Avoids face-to-face/V-CIP</li>
          <li>Unreasonable urgency</li>
          <li>Attempts to bypass procedures</li>
          <li>Unwilling to declare PEP status</li>
          <li>Unusual AML knowledge</li>
        </ul>

        <h5>(c) Profile Inconsistencies:</h5>
        <ul className="legal-list">
          <li>Occupation inconsistent with financial profile</li>
          <li>Address mismatch to socio-economic profile</li>
          <li>Disposable email/phone</li>
          <li>No digital footprint</li>
          <li>Employment discrepancies</li>
          <li>Age vs sophistication mismatch</li>
        </ul>

        {/* 9.1.2 Transaction Behavior */}
        <h4>9.1.2 Transaction Behavior Red Flags</h4>

        <h5>(a) Urgency and Pressure:</h5>
        <ul className="legal-list">
          <li>Insists on immediate execution</li>
          <li>Pressures staff to bypass checks</li>
          <li>Threatens to switch platforms</li>
          <li>Exploit timing</li>
        </ul>

        <h5>(b) Lack of Economic Rationale:</h5>
        <ul className="legal-list">
          <li>No investment rationale</li>
          <li>Inconsistent with risk appetite</li>
          <li>Overpriced purchases</li>
          <li>Discounted selling</li>
          <li>No commercial sense in timing</li>
        </ul>

        <h5>(c) Indifference to Terms:</h5>
        <ul className="legal-list">
          <li>No interest in valuation or rights</li>
          <li>Accepts unfavorable terms</li>
          <li>Focused only on completion</li>
        </ul>

        {/* 9.2 Transaction Pattern Red Flags */}
        <h3>9.2 Transaction Pattern Red Flags</h3>

        <h4>9.2.1 Structuring and Layering Indicators</h4>

        <h5>(a) Structuring (Smurfing):</h5>
        <ul className="legal-list">
          <li>Just-below-threshold transactions</li>
          <li>Split across family/related parties</li>
          <li>Sequential similar transactions</li>
          <li>Round numbers</li>
          <li>Timing to avoid detection</li>
        </ul>

        <h5>(b) Layering:</h5>
        <ul className="legal-list">
          <li>Rapid buy/sell</li>
          <li>No holding period</li>
          <li>Multiple accounts</li>
          <li>Multiple intermediaries</li>
          <li>Complex structures</li>
        </ul>

        <h5>(c) Circular Transactions:</h5>
        <ul className="legal-list">
          <li>Buy from A, sell to B</li>
          <li>Repeated among same group</li>
          <li>Funds appear to circulate</li>
        </ul>

        {/* 9.2.2 Value Transfer Indicators */}
        <h4>9.2.2 Value Transfer Indicators</h4>

        <h5>(a) Valuation Anomalies:</h5>
        <ul className="legal-list">
          <li>Price deviates from fair value</li>
          <li>Manipulated valuation</li>
          <li>Non-arm's-length pricing</li>
        </ul>

        <h5>(b) Trade-Based ML Indicators:</h5>
        <ul className="legal-list">
          <li>Over-invoicing</li>
          <li>Under-invoicing</li>
          <li>Multiple invoicing</li>
          <li>Phantom transactions</li>
        </ul>

        {/* 9.2.3 Fund Flow Red Flags */}
        <h4>9.2.3 Fund Flow Red Flags</h4>

        <h5>(a) Source of Funds Concerns:</h5>
        <ul className="legal-list">
          <li>High-risk jurisdiction origin</li>
          <li>Multiple accounts payment</li>
          <li>New bank accounts</li>
          <li>Third-party payments</li>
          <li>Frequent cash deposits</li>
          <li>Unidentified lender</li>
        </ul>

        <h5>(b) Destination of Funds:</h5>
        <ul className="legal-list">
          <li>Immediate transfer to third parties</li>
          <li>Offshore transfers</li>
          <li>Dispersed into multiple accounts</li>
          <li>Requests for payout to third party</li>
          <li>Multiple jurisdictions routing</li>
        </ul>

        <h5>(c) Transaction Velocity:</h5>
        <ul className="legal-list">
          <li>Funds received → invested same day</li>
          <li>Immediate liquidation</li>
          <li>High-frequency trades vs occupation</li>
        </ul>

        {/* 9.3 Counterparty & Relationship Red Flags */}
        <h3>9.3 Counterparty and Relationship Red Flags</h3>

        <h4>9.3.1 Seller/Issuer Red Flags</h4>
        <ul className="legal-list">
          <li>Individual with large holdings across multiple unlisted companies</li>
          <li>Frequent sales (unauthorized dealer)</li>
          <li>Suspicious issuer characteristics</li>
          <li>Opaque ownership</li>
          <li>Tax-haven incorporation</li>
          <li>Off-platform insistence</li>
          <li>Unwilling to provide documentation</li>
        </ul>

        <h4>9.3.2 Buyer Red Flags</h4>
        <ul className="legal-list">
          <li>Buys distressed/defunct company securities</li>
          <li>Accumulates stake beyond thresholds</li>
          <li>Acts with syndicate</li>
          <li>Accepts terms against self-interest</li>
          <li>Multiple buyers from same seller</li>
        </ul>

        <h4>9.3.3 Intermediary Red Flags</h4>
        <ul className="legal-list">
          <li>Unlicensed intermediary</li>
          <li>Reluctant to disclose identity</li>
          <li>Repeated introductions</li>
          <li>Acts as principal</li>
          <li>Insists on anonymity</li>
        </ul>

        {/* 9.4 Geographic & Jurisdictional Red Flags */}
        <h3>9.4 Geographic and Jurisdictional Red Flags</h3>

        <h4>9.4.1 High-Risk Jurisdiction Indicators</h4>
        <ul className="legal-list">
          <li>Customer/BO/counterparty from FATF high-risk</li>
          <li>Funds routed via secrecy jurisdictions</li>
          <li>Tax-haven corporate structures</li>
          <li>Routing via conflict zones</li>
        </ul>

        <h4>9.4.2 Cross-Border Transaction Red Flags</h4>
        <ul className="legal-list">
          <li>Amount inconsistent with declared purpose</li>
          <li>No jurisdictional link</li>
          <li>Multiple correspondent banks</li>
          <li>Bank secrecy routing</li>
          <li>Designed to avoid FEMA</li>
          <li>Maximum utilization of LRS limits</li>
        </ul>

        {/* 9.5 Pre-IPO Market Red Flags */}
        <h3>9.5 Specific Pre-IPO Market Red Flags</h3>

        <h4>9.5.1 Pre-IPO Arbitrage Exploitation</h4>
        <ul className="legal-list">
          <li>Inside information indicators</li>
          <li>Investments timed before IPO announcements</li>
          <li>Issuer company connections undisclosed</li>
          <li>Pattern of pre-IPO timing</li>
        </ul>

        <h4>9.5.2 SEBI Regulation Circumvention</h4>
        <ul className="legal-list">
          <li>Avoiding SAST, insider trading, ICDR norms</li>
          <li>Multiple entities accumulating stake</li>
          <li>Timing circumventing lock-in</li>
        </ul>

        <h4>9.5.3 Control and Influence Indicators</h4>
        <ul className="legal-list">
          <li>Stake ≥10% without intention disclosure</li>
          <li>Shareholders' agreements indicating hidden control</li>
          <li>Acting-in-concert patterns</li>
          <li>Avoiding SBO disclosure</li>
        </ul>

        <h4>9.5.4 Distressed Company Red Flags</h4>
        <ul className="legal-list">
          <li>Companies under probe</li>
          <li>NCLT/IBC entities</li>
          <li>Qualified audit reports</li>
          <li>Fraud/default indicators</li>
        </ul>

        <h4>9.5.5 ESOP Red Flags</h4>
        <ul className="legal-list">
          <li>Immediate post-vesting purchases</li>
          <li>Multiple employees selling simultaneously</li>
          <li>Price deviates from exercise price</li>
          <li>Patterns suggesting unlicensed dealing</li>
        </ul>

      </section>

      {/* 10. SUSPICIOUS TRANSACTION REPORTING */}
      <section id="str" className="section">
        <div className="section-header">
          <span className="section-number">10</span>
          <h2 className="section-title">Suspicious Transaction Reporting (STR)</h2>
        </div>

        <h3>10.1 Legal Framework and Obligations</h3>

        <h4>10.1.1 Statutory Mandate</h4>
        <p>The Platform shall:</p>

        <ul className="legal-list">
          <li>(a) Maintain system for reporting suspicious transactions;</li>
          <li>(b) Furnish attempted or executed suspicious transactions to FIU-IND;</li>
          <li>(c) File reports within prescribed timelines.</li>
        </ul>

        <h5>Suspicious if:</h5>
        <ul className="legal-list">
          <li>Proceeds of crime involved</li>
          <li>Terrorist financing indicators</li>
          <li>Structuring to avoid requirements</li>
          <li>No economic rationale</li>
        </ul>

        <h4>10.1.2 Definition of Suspicious Transaction</h4>
        <p>A suspicious transaction includes:</p>

        <ul className="legal-list">
          <li>(a) Proceeds of crime</li>
          <li>(b) Terrorist financing</li>
          <li>(c) Structuring/smurfing</li>
          <li>(d) No economic rationale</li>
          <li>(e) Attempted suspicious transactions</li>
        </ul>

        <h4>10.1.3 “Reasonable Grounds to Suspect” Standard</h4>

        <ul className="legal-list">
          <li>(a) Facts suggesting reasonable suspicion</li>
          <li>(b) Objective assessment</li>
          <li>(c) No need for proof</li>
          <li>(d) When in doubt, report</li>
        </ul>

        {/* 10.2 Identification of Suspicious Transactions */}
        <h3>10.2 Identification of Suspicious Transactions</h3>

        <h4>10.2.1 Sources of Suspicion</h4>

        <h5>(a) Automated Monitoring:</h5>
        <ul className="legal-list">
          <li>Red flags from rules</li>
          <li>Pattern detection</li>
          <li>Threshold alerts</li>
        </ul>

        <h5>(b) Manual Review:</h5>
        <ul className="legal-list">
          <li>Investigation of yellow/red alerts</li>
          <li>Periodic account reviews</li>
          <li>Customer interactions</li>
          <li>Pattern analysis</li>
        </ul>

        <h5>(c) Front-Line Staff:</h5>
        <ul className="legal-list">
          <li>Observed unusual behavior</li>
          <li>Customer statements</li>
          <li>KYC inconsistencies</li>
        </ul>

        <h5>(d) External Intelligence:</h5>
        <ul className="legal-list">
          <li>FIU-IND advisories</li>
          <li>Law enforcement information</li>
          <li>Media reports</li>
          <li>Information from other institutions</li>
        </ul>

        <h5>(e) Third-Party Reports:</h5>
        <ul className="legal-list">
          <li>Counterparty concerns</li>
          <li>Complaints</li>
          <li>Whistleblower reports</li>
          <li>Legal/compliance advisors</li>
        </ul>

      </section>

    </div>
  );
}
